const Constants = {
    BASE_URL: 'http://api-lulu.hibitbyte.com',
    MY_KEY: '',
    ACTION_FETCH_PRODUCTLIST: 'ACTION_FETCH_PRODUCTLIST',
    ACTION_FETCH_PRODUCTLIST_MORE:'ACTION_FETCH_PRODUCTLIST_MORE',
    ACTION_SORT_PRODUCTLIST: 'ACTION_SORT_PRODUCTLIST',
    ACTION_FETCH_FILTERS: 'ACTION_FETCH_FILTERS',
    ACTION_FETCH_PRODUCT_DETAIL: 'ACTION_FETCH_PRODUCT_DETAIL'

}

export default Constants