const Constants = {
    BASE_URL: 'http://api-lulu.hibitbyte.com',
    MY_KEY: 'rtIpbFi4fzjisRJNgqEtyR4Ags/Yz15jsqAGhE6uXIFkTG7vUSJ/yRYXiqrnlKjfTA2kAUtChiIflImPe/T3uA==',
    ACTION_FETCH_PRODUCTLIST: 'ACTION_FETCH_PRODUCTLIST',
    ACTION_FETCH_PRODUCTLIST_MORE:'ACTION_FETCH_PRODUCTLIST_MORE',
    ACTION_FETCH_FILTERS: 'ACTION_FETCH_FILTERS',

}

export default Constants